In [1]:
text = ['this is a line','this is an other line','complitly different line']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
cv = CountVectorizer()

In [4]:
sparce_matrix  =  cv.fit_transform(text)

In [5]:
sparce_matrix

<3x7 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [6]:
sparce_matrix.todense()

matrix([[0, 0, 0, 1, 1, 0, 1],
        [1, 0, 0, 1, 1, 1, 1],
        [0, 1, 1, 0, 1, 0, 0]], dtype=int64)

In [7]:
cv_2 = CountVectorizer(stop_words='english') 

In [8]:
sparce_matrix_2 = cv_2.fit_transform(text)

In [9]:
sparce_matrix_2.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [10]:
cv_2.vocabulary_

{'line': 2, 'complitly': 0, 'different': 1}

In [11]:
cv.vocabulary_

{'this': 6,
 'is': 3,
 'line': 4,
 'an': 0,
 'other': 5,
 'complitly': 1,
 'different': 2}

In [12]:
from sklearn.feature_extraction.text import TfidfTransformer

In [13]:
rfidft = TfidfTransformer()

In [15]:
test =  rfidft.fit_transform(sparce_matrix)

In [16]:
test.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.        , 0.61980538],
        [0.53409337, 0.        , 0.        , 0.40619178, 0.31544415,
         0.53409337, 0.40619178],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        , 0.        ]])

In [17]:
# we can do that directly without calling vectorizing than transformer :

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
tfidv = TfidfVectorizer()

In [20]:
result =  tfidv.fit_transform(text)

In [21]:
result.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.        , 0.61980538],
        [0.53409337, 0.        , 0.        , 0.40619178, 0.31544415,
         0.53409337, 0.40619178],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        , 0.        ]])